server:
  port: 8761
spring:
  application:
    name: eureka-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

