server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio-user
          uri: lb://MICROSERVICIO-USER
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: microservicio-car
          uri: lb://MICROSERVICIO-CAR
          predicates:
            - Path=/cars/**
          filters:
            - AuthFilter
        - id: microservicio-bike
          uri: lb://MICROSERVICIO-BIKE
          predicates:
            - Path=/bikes/**
          filters:
            - AuthFilter
        - id: microservicio-auth
          uri: lb://MICROSERVICIO-AUTH
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
