server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicio-user
          uri: lb://microservicio-user
          predicates:
            - Path=/users/**
        - id: microservicio-car
          uri: lb://microservicio-car
          predicates:
            - Path=/cars/**
        - id: microservicio-bike
          uri: lb://microservicio-bike
          predicates:
            - Path=/bikes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
