server:
  port: 8081
spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-data
        git:
          default-label: mongodb
          uri: https://github.com/sergioyanez/microservicios


